apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: instance
spec:
  compositeTypeRef:
    apiVersion: aws.example.org/v1alpha1
    kind: CompositeCompute
  resources:
    - name: instance
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            subnetIdSelector: {}
            instanceType: t3.micro
        providerConfigRef:
          name: user-keys
      patches:
        - fromFieldPath: "spec.subnetSelector.matchLabels"
          toFieldPath: "spec.forProvider.subnetIdSelector.matchLabels"
        - fromFieldPath: "status.atProvider.privateIpAddress"
          toFieldPath: "status.instanceIP"
