apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.aws.example.org
spec:
  group: aws.example.org
  names:
    kind: xNetwork
    plural: xnetworks
  claimNames:
    kind: Network
    plural: networks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      additionalPrinterColumns:
        - name: VPC CIDR
          type: string
          jsonPath: .status.vpcCidrBlock
          priority: 1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
            status:
              type: object
              properties:
                vpcCidrBlock:
                  type: string
                subnetCIDRs:
                  type: array
                  items:
                    type: string
                subnetAZs:
                  type: array
                  items:
                    type: string
  # This will limit what secrets are listed in claim
  # connectionSecretKeys:
  #   - cidrBlock
