{{- range .Values.subnets }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: demo-simple-subnet-{{ .az }}
  labels:
    app: demo-simple
    az: {{ .az }}
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        app: demo-simple
    cidrBlock: {{ .cidr }}
    region: us-east-1
    availabilityZone: us-east-{{ .az }}
    tags:
      Name: demo-simple-{{ .az }}
      az: {{ .az }}
  providerConfigRef:
    name: user-keys
{{- end }}