apiVersion: aws.example.org/v1alpha1
kind: Compute
metadata:
  name: compute-y
spec:
  subnetSelector:
    matchLabels:
      app: xdemo
      az: 1b
  instanceType: t3.micro
  ami: ami-01edd5711cfe3825c
  state: running # default: stopped
