apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcomputes.aws.example.org
spec:
  group: aws.example.org
  names:
    kind: xCompute
    plural: xcomputes
    shortNames:
      - cmp
  claimNames:
    kind: Compute
    plural: computes
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      additionalPrinterColumns:
        - name: IpAddress
          type: string
          jsonPath: .status.privateIp
          priority: 1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                subnetSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                instanceType:
                  type: string
                ami:
                  type: string
                # Other instance properties...
            status:
              type: object
              properties:
                privateIp:
                  type: string
