apiVersion: ec2.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: demo-compute-instance-web
  labels:
    app: demo
    environment: development
    project: crossplane-demo
    type: web-server
spec:
  forProvider:
    instanceType: t2.micro    # Free Tier-eligible instance type[17][15]
    ami: ami-01edd5711cfe3825c
    region: us-east-1         # Must match your ProviderConfig region
    tags:
      Name: demo-compute-instance-web
      Environment: development
      Project: crossplane-demo
      Owner: demo-team
      Type: web-server
    subnetIdSelector:
      matchLabels:
        app: demo
        environment: development
        az: 1a
  providerConfigRef:
    name: user-keys
