apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: demo-vpc
  labels:
    app: demo
spec:
  forProvider:
    cidrBlock: 192.168.0.0/24
    region: us-east-1         # Adjust as needed
    tags:
      Name: demo
  providerConfigRef:
    name: user-keys
